name: Code Review

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cpplint
      run: |
        sudo apt-get install python3-pip
        pip3 install cpplint
    - name: Run cpplint
      run: |
        cpplint --recursive .
