name: Generate Code Suggestions
on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action every day at midnight
  workflow_dispatch:  # This allows you to manually trigger the action
jobs:
  generate_suggestions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      REPO_NAME: ${{ github.repository }}
      OWNER_NAME: ${{ github.repository_owner }}
      OPENAI_API_KEY: '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'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub  # This is a Python library for the GitHub API
    - name: Generate and post code suggestions
      run: python .github/scripts/generate_suggestions.py
