name: Code Quality Check

on: [push]

jobs:
  quality_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy

    - name: Run clang-tidy
      run: clang-tidy -checks=-*,readability-identifier-naming -config='{CheckOptions: [{key: readability-identifier-naming.TypeCase, value: CamelCase}]}' *.cpp
